### PR TITLE
Load JavaScript From PayPal Asynchronously

### LINKED ISSUE #10: Paypal Load Dependency Failing
We have implemented the latest version of this plugin(3.0.0) and we're receiving some weird behavior when accessing the site, it looks like there might be a PayPal load dependency that is failing. Since this is failing the load times for our site have become extremely long, I don't have the stack trace for the issue, but I will update this once it's received, thanks

### PR DESCRIPTION
**Pull request by tubbo**
Screen Shot 2020-07-22 at 12 57 23 PM

Using the `async` attribute in the `<script>` tag that loads PayPal's JavaScript code, Workarea can now prevent it blocking the page in case of a failure, and improve load time performance to boot.

Fixes #10

### CODE REVIEW

**Comment by mttdffy** [comment]
Does this not interfere with the workarea modules that try to use the `window.paypal` object? What if it loads but after those modules try to instantiate? They're written to fail gracefully if `window.paypal` is undefined but thats there in case of total failure, not just a delay in loading. We ideally need a way to know when paypal finishes loading to then trigger the modules that need it.

**Comment by tubbo** [comment]
@mttdffy Indeed, after setting `async` on the `<script>` tag, my first load of the page did not display the PayPal button on the cart page. Since the `async` property also caches the request once it's done, a simple page refresh got the button back. But I can see how this would be an issue in the real world.

I might be down the wrong path here, but I can't see anywhere in [PayPal's documentation](https://developer.paypal.com/docs/checkout/troubleshoot/performance/#instant-render) that indicates any events are being broadcast to the `window` or `document` object once the PayPal SDK is done loading. So if that's true, we have a few options:

**Option 1, Poll for changes:** If a PayPal `<script>` tag is in the DOM, we will assume that the PayPal SDK is expected to be loaded at some point, so we'll use `setTimeout` to call `init()` every N seconds until `window.paypal` is available to us. This could also be a config that's loaded from ERB, but I figured just testing for the tag's existence would give us the same result. I actually tried this locally and it not only works, it also doesn't seem to block the rest of the page load even when I clear my cache. So that's nice. 
**Option 3, Load the SDK from a JS module:** This is a pattern that we use on other plugins, such as Listrak, and involves sending a custom event to `window` that the rest of the PayPal modules can listen on, and wait to initialize the module until the SDK is available. By far the cleanest approach, but definitely requires the most amount of changes. For example, I'll have to either refactor or move the code out of `PaypalHelper` that determines the URL and attributes for the `<script>` tag. I haven't tried this yet but I'm pretty sure it will work, as we've done it a few times in the past.

To test this stuff out, I'm providing bogus credentials in config. This simulates `window.paypal` not loading in time, as well as the SDK being unavailable because PayPal is down.

Choose Your Fate, Warrior.

**Comment by mttdffy** [comment]
@tubbo pretty curious what invisible option 2 is. 

Uh.. option 1 sounds similar to what I was thinking. Not sure how terrible that would be from a cat jesus perspective. There is a lot of critical info getting put together in that helper method that I would rather not mess with.

**Comment by bencrouse** [comment]
I had the same initial concern, but they make a good point about the real world in their docs: "For a bonus performance boost, load the PayPal script asynchronously on a page that precedes the Checkout page. This approach pre-caches the script, making future loads/renders instantaneous"

Options 1 or 3 seem like easy enough insurance against this not being the case, but will need to review option 2.

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js [hunk 1]
```diff
@@ -57,9 +57,17 @@ WORKAREA.registerModule('paypalButtons', (function () {
          * @memberof WORKAREA.paypalButtons
          */
         init = function ($scope) {
-            var $buttonContainer = $('#paypal-button-container', $scope);
+            var $buttonContainer = $('#paypal-button-container', $scope),
+                paypalNotLoaded = window.paypal === undefined,
+                paypalExpectedToLoad = !_.isEmpty(
```
Comment (tubbo) [inline app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js]: According to the `include_paypal_javascript_tag` helper method, the `<script>` tag won't even render if the gateway is not configured.

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+         * @name init
+         * @memberof WORKAREA.paypal
+         */
+        init = function() {
+            var $sdk = $('script[data-partner-attribution-id]'),
+                paypalLoaded = window.paypal !== undefined,
+                paypalExpectedToLoad = !_.isEmpty($sdk);
+
+            if (!paypalLoaded && paypalExpectedToLoad) {
+                window.setTimeout(init, 5000);
```
Comment (mttdffy) [inline app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js]: is 5 seconds too long? Also, this should probably stop checking after so long. If the script becomes unavailable and never loads then this just keeps running. I think maybe 2 second timeout? With maybe a limit of doing that 5-10 times? If after 20(ish) seconds its not loaded its probably not going to.

**Review by mttdffy — CHANGES_REQUESTED** [review]

**Review by bencrouse — CHANGES_REQUESTED** [review]
See @mttdffy 's comment

File: config/initializers/append_points.rb [hunk 3]
```diff
@@ -25,6 +25,7 @@
 
 Workarea::Plugin.append_javascripts(
   'storefront.modules',
+  'workarea/storefront/paypal/modules/paypal',
```
Comment (mttdffy) [inline config/initializers/append_points.rb:28]: wondering if this module should be last. Assuming modules are initialized in order and the paypal sdk has already loaded, the `paypal` module will init, try to call all the `handlers` (there will be none), and then move on. Then, the other modules will init and add themselves to the handlers list, which will never get called until/if `WORKAREA.initModules` is called again for something else. Right?

**Review by mttdffy — APPROVED** [review]

File: config/initializers/append_points.rb (hunk 3 above)
Comment (bencrouse) [reply config/initializers/append_points.rb:28]: That's a good point, but also the other modules need to be able to call the `ready` method to add their handlers. Maybe running the handlers should be in a `setTimeout(..., 0)` or something?

**Review by bencrouse — CHANGES_REQUESTED** [review]

File: config/initializers/append_points.rb (hunk 3 above)
Comment (tubbo) [reply config/initializers/append_points.rb:28]: I should probably just modify `ready()` to call the function immediately if `paypalLoaded`.

Comment (mttdffy) [reply config/initializers/append_points.rb:28]: calling `ready` isn't a problem if they are loaded before the `WORKAREA.paypal` because they load, then initialize. So `WORKAREA.paypal.ready` will exist before its initialization method is called

Comment (tubbo) [reply config/initializers/append_points.rb:28]: I talked with Duffy on Slack about this a bit and we came to the conclusion that yes, this will most likely be a problem in the real world. To resolve this issue, the `init()` functions in the PayPal modules have been changed to just be calls to `WORKAREA.paypal.ready()`, which will call them on its own `init()` when PayPal has been loaded. This should also happen every time `initModules` is called, such as during an ajax request.

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+            var $sdk = $('script[data-partner-attribution-id]'),
+                paypalLoaded = window.paypal !== undefined,
+                paypalExpectedToLoad = !_.isEmpty($sdk);
+
+            attempts += 1;
+
+            if (!paypalLoaded && paypalExpectedToLoad && attempts <= 20) {
+                window.setTimeout(init, 2000);
+            } else if (paypalLoaded) {
+                handlers.forEach(function(handler) { handler($scope); });
```
Comment (tubbo) [inline app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js]: we're now passing the `$scope` thru here so other paypal modules can use `WORKAREA.paypal.ready()` as a replacement for their own `init()` functions.

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js [hunk 5]
```diff
@@ -49,23 +49,15 @@ WORKAREA.registerModule('paypalButtons', (function () {
...
             if (_.isEmpty($buttonContainer)) { return; }
 
             setup($buttonContainer);
-        };
+        });
 
-    return {
-        init: init
-    };
+    return {};
```
Comment (tubbo) [inline app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js]: do I need this at the bottom, or can these modules just not return anything and that's OK?

Comment (bencrouse) [reply app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js]: I dunno, I would probably do this as a just-in-case:
```
  return {
    init: $.noop
  }
```

File: config/initializers/append_points.rb (hunk 3 above)
Comment (bencrouse) [reply config/initializers/append_points.rb:28]: Sounds good. Although it seems like to follow conventions, registering the PayPal stuff with `WORKAREA.paypal.ready` would just be part of the init for those modules:
```
  return {
    init: _.once(function () {
      WORKAREA.paypal.ready(function() {
        / * ... */
      });
    })
  }
```

**Review by bencrouse — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js (hunk 5 above)
Comment (tubbo) [reply app/assets/javascripts/workarea/storefront/paypal/modules/paypal_buttons.js]: Just confirmed that removing this doesn't seem to have an effect, so I'm doing it.

File: config/initializers/append_points.rb (hunk 3 above)
Comment (tubbo) [reply config/initializers/append_points.rb:28]: That would still pose the problem of the external `<script>` not being loaded in time, as the module `init()` functions will be run _after_ PayPal's `init()`.

Comment (bencrouse) [reply config/initializers/append_points.rb:28]: Oh I see the confusion - if I call `WORKAREA.paypal.ready` _after_ PayPal has been loaded, it won't run what I've passed. I think that's a fair expectation of how a `ready` works. jQuery and the affirm API are two examples.

**Review by bencrouse — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+            var $sdk = $('script[data-partner-attribution-id]'),
+                paypalExpectedToLoad = !_.isEmpty($sdk);
+
+            attempts += 1;
+            paypalLoaded = window.paypal !== undefined;
+
+            if (!paypalLoaded && paypalExpectedToLoad && attempts <= 20) {
+                window.setTimeout(init, 2000);
+            } else if (paypalLoaded) {
+                _.each(handlers, function(handler) { handler(); });
```
Comment (mttdffy) [inline app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js:54]: think handlers should be cleared out after this. Otherwise any secondary initialization of modules will refire those, which we wouldn't want, right?

**Review by mttdffy — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js (hunk 6 above)
Comment (tubbo) [reply app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js:54]: If `initModules` gets fired twice, it would be on a different `$scope`, so yes we *would* want the handlers to fire again for a different DOM tree...

Comment (mttdffy) [reply app/assets/javascripts/workarea/storefront/paypal/modules/paypal.js:54]: nope. You are defining the handlers with a fixed scope. So you wouldn't want them to fire again, as they would always fire with the same scope as defined. Then the modules (button and hosted fields) would init again, adding a second handler for the same module with a different scope, or more likely just fire off immediately since PayPal would likely be loaded by the time another `initModules` was called.

**Comment by tubbo** [comment]
`bundler-audit` will probably fail on this until workarea-commerce/workarea#483 is merged.

**Review by bencrouse — APPROVED** [review]

**Comment by bencrouse** [comment]
@mttdffy you see the latest version?

**Review by mttdffy — APPROVED** [review]
